language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -U crosscompute
  - pip install -U pandas
  - cd integer && pip install -e .
  - cd text && pip install -e .
  - cd table && pip install -e .
  - cd image && pip install -e .
  - cd geotable && pip install -e .
script: pytest
