language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -U crosscompute

  - pushd integer 
  - pip install -e .
  - popd

  - pushd text
  - pip install -e .
  - popd

  - pushd table
  - pip install -e .
  - popd

  - pushd image
  - pip install -e .
  - popd

  - pushd geotable
  - pip install -e .
  - popd
script: py.test
